### ISSUE TITLE
rqt_moveit: load error 

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_robot_plugins#77]
When loading rqt_moveit it does not load and instead shows this error:
`
PluginManager._load_plugin() could not load plugin "rqt_moveit/Moveit":
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
    self._load()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 94, in load
    return class_ref(plugin_context)
  File "/home/ablasdel/workspace/src/rqt_robot_plugins/rqt_moveit/src/rqt_moveit/moveit_plugin.py", line 47, in __init__
    self._moveit_widget = MoveitWidget(self, plugin_context)
  File "/home/ablasdel/workspace/src/rqt_robot_plugins/rqt_moveit/src/rqt_moveit/moveit_widget.py", line 111, in __init__
    self.sig_sysmsg = self._widget_topic.sig_sysmsg
AttributeError: 'TopicWidget' object has no attribute 'sig_sysmsg'
`

**Comment by k-okada** [comment]
any update on this? we have same problem on indigo

**Comment by ablasdel** [comment]
No but I'll give it a look if I get a chance.

**Comment by ablasdel** [comment]
I'm not realistically going to get the free time to debug this soon so I will remove myself as Assignee

**Comment by dirk-thomas** [comment]
Should be fixed by #119.
